"""
Type stubs for football_cv._core native C++ extension.
"""

from collections.abc import Sequence
from typing import overload

import numpy as np

class Point2D:
    x: float
    y: float

    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    def distance_to(self, other: Point2D) -> float: ...
    def displacement_from(self, other: Point2D) -> tuple[float, float]: ...
    def is_finite(self) -> bool: ...
    def to_tuple(self) -> tuple[float, float]: ...
    def to_numpy(self) -> np.ndarray: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class BoundingBox:
    x1: float
    y1: float
    x2: float
    y2: float

    def __init__(
        self, x1: float = 0.0, y1: float = 0.0, x2: float = 0.0, y2: float = 0.0
    ) -> None: ...
    def center(self) -> Point2D: ...
    def foot_position(self) -> Point2D: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def area(self) -> float: ...
    def is_valid(self) -> bool: ...
    def is_finite(self) -> bool: ...
    def contains(self, pt: Point2D) -> bool: ...
    def to_tuple(self) -> tuple[float, float, float, float]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, idx: int) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class CameraMotion:
    dx: float
    dy: float
    is_scene_cut: bool

    def __init__(
        self, dx: float = 0.0, dy: float = 0.0, is_scene_cut: bool = False
    ) -> None: ...
    def to_tuple(self) -> tuple[float, float]: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

def get_center_of_bbox(bbox: BoundingBox) -> Point2D: ...
def get_foot_position(bbox: BoundingBox) -> Point2D: ...
def get_bbox_width(bbox: BoundingBox) -> float: ...
def get_bbox_height(bbox: BoundingBox) -> float: ...
def measure_distance(p1: Point2D, p2: Point2D) -> float: ...
def measure_xy_distance(p1: Point2D, p2: Point2D) -> tuple[float, float]: ...
def extract_centers(bboxes: Sequence[BoundingBox]) -> list[Point2D]: ...
def extract_foot_positions(bboxes: Sequence[BoundingBox]) -> list[Point2D]: ...
def filter_valid_bboxes(bboxes: Sequence[BoundingBox]) -> list[BoundingBox]: ...
def find_nearest_point(
    target: Point2D,
    candidates: Sequence[Point2D],
    max_distance: float = ...,
) -> int | None: ...

class PerspectiveTransformer:
    def __init__(
        self,
        pixel_vertices: Sequence[Point2D | Sequence[float]] | np.ndarray | None = None,
        court_width: float = 68.0,
        court_length: float = 23.32,
    ) -> None: ...
    @overload
    def transform_point(
        self, point: Point2D | Sequence[float] | np.ndarray
    ) -> Point2D | None: ...
    @overload
    def transform_point(self, x: float, y: float) -> Point2D | None: ...
    def transform_points(
        self, points: Sequence[Point2D | Sequence[float]] | np.ndarray
    ) -> list[Point2D | None]: ...
    def is_point_inside(
        self, point: Point2D | Sequence[float] | np.ndarray
    ) -> bool: ...
    @property
    def court_width(self) -> float: ...
    @property
    def court_length(self) -> float: ...
    @property
    def pixel_vertices(self) -> list[Point2D]: ...
    @property
    def homography_matrix(self) -> np.ndarray: ...
    @staticmethod
    def default_pixel_vertices() -> list[Point2D]: ...

class CameraMotionEstimator:
    def __init__(
        self, minimum_distance: float = 5.0, scene_cut_threshold: float = 80.0
    ) -> None: ...
    def estimate_from_features(
        self,
        old_features: Sequence[Point2D] | np.ndarray,
        new_features: Sequence[Point2D] | np.ndarray,
    ) -> CameraMotion: ...
    @staticmethod
    def filter_margin_points(
        points: Sequence[Point2D] | np.ndarray,
        frame_width: float,
        left_margin_width: float = 20.0,
        right_margin_start: float = 900.0,
        right_margin_end: float = 1050.0,
    ) -> list[Point2D]: ...
    @staticmethod
    def accumulate_motion(
        motion_steps: Sequence[CameraMotion],
    ) -> list[Point2D]: ...
    @property
    def minimum_distance(self) -> float: ...
    @property
    def scene_cut_threshold(self) -> float: ...
